#!groovy

// Generated by IBM TransformationAdvisor
// Wed May 15 09:42:20 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}